name: Build

on:
  push:
    branches: [ "**" ]

env:
  GH_JVM_OPTS: "-Xss64m -Xms1024m -XX:MaxMetaspaceSize=2G -Xmx4G"

jobs:

  build_java_project:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { name: "Scala 2", version: "2.13.11", binary-version: "2.13", java-version: "11", java-distribution: "temurin" }

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.scala.java-version }}
        distribution: ${{ matrix.scala.java-distribution }}
        cache: sbt
    - uses: sbt/setup-sbt@v1

    - name: "[Push] Build All for ${{ matrix.scala.name }} v${{ matrix.scala.version }} - ${{ github.run_number }}"
      if: github.event_name == 'push'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        CURRENT_BRANCH_NAME: ${{ github.ref }}
        RUN_ID: ${{ github.run_id }}
        RUN_NUMBER: ${{ github.run_number }}
        JVM_OPTS: ${{ env.GH_JVM_OPTS }}
      run: |
        echo "[BEFORE]CURRENT_BRANCH_NAME=${CURRENT_BRANCH_NAME}"
        export CURRENT_BRANCH_NAME="${CURRENT_BRANCH_NAME#refs/heads/}"
        echo " [AFTER]CURRENT_BRANCH_NAME=${CURRENT_BRANCH_NAME}"
        echo "RUN_ID=${RUN_ID}"
        echo "RUN_NUMBER=${RUN_NUMBER}"
        echo "Push #${PUSH_NUMBER}"
        java -version
        echo "JVM_OPTS=${JVM_OPTS}"
        echo "SBT_OPTS=${SBT_OPTS}"

        export CI_BRANCH="${GITHUB_REF#refs/heads/}"
        .github/workflows/sbt-build.sh ${{ matrix.scala.version }}


    - name: "[PR] Build All for ${{ matrix.scala.name }} v${{ matrix.scala.version }} - PR-#${{ github.event.pull_request.number }} - ${{ github.run_number }}"
      if: github.event_name == 'pull_request'
      env:
        CURRENT_BRANCH_NAME: ${{ github.base_ref }}
        RUN_ID: ${{ github.run_id }}
        RUN_NUMBER: ${{ github.run_number }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        JVM_OPTS: ${{ env.GH_JVM_OPTS }}
      run: |
        echo "Pull request to the '${CURRENT_BRANCH_NAME}' branch"
        echo "RUN_ID=${RUN_ID}"
        echo "RUN_NUMBER=${RUN_NUMBER}"
        echo "PR #${PR_NUMBER}"
        java -version
        echo "JVM_OPTS=${JVM_OPTS}"
        echo "SBT_OPTS=${SBT_OPTS}"
        
        .github/workflows/sbt-build.sh ${{ matrix.scala.version }}
