name: Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { name: "Scala 2", version: "2.13.11", binary-version: "2.13", java-version: "11", java-distribution: "temurin" }

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.scala.java-version }}
        distribution: ${{ matrix.scala.java-distribution }}

    - name: Cache SBT
      uses: actions/cache@v3.3.1
      with:
        path: |
          ~/.ivy2/cache
          ~/.cache/coursier
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
        restore-keys: |
          ${{ runner.os }}-sbt

    - name: sbt GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_AUTH_TOKEN_GITHUB }}
      run: |
        echo "Run] sbt GitHub release"
        echo 'sbt -J-Xmx2048m devOopsGitHubRelease'
        sbt \
          -J-XX:MaxMetaspaceSize=1024m \
          -J-Xmx2048m \
          devOopsGitHubRelease

    - name: sbt Publish
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.RELEASE_AUTH_TOKEN_GITHUB }}
      run: |
        echo "Run] sbt ci-release"
        export SOURCE_DATE_EPOCH=$(date +%s)
        echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH"
        echo 'sbt -J-XX:MaxMetaspaceSize=1024m -J-Xmx2048m -v clean +test +packagedArtifacts ci-release devOopsGitHubReleaseUploadArtifacts'
        sbt \
        -J-XX:MaxMetaspaceSize=1024m \
        -J-Xmx2048m \
        -v \
        clean \
        compile \
        packagedArtifacts \
        ci-release

  publish-snapshot:
    if: startsWith(github.ref, 'refs/heads/')

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { name: "Scala 2", version: "2.13.11", binary-version: "2.13", java-version: "11", java-distribution: "temurin" }

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.scala.java-version }}
        distribution: ${{ matrix.scala.java-distribution }}

    - name: Cache SBT
      uses: actions/cache@v3.3.1
      with:
        path: |
          ~/.ivy2/cache
          ~/.cache/coursier
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
        restore-keys: |
          ${{ runner.os }}-sbt

    - name: sbt Publish
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.RELEASE_AUTH_TOKEN_GITHUB }}
      run: |
        echo "Run] sbt ci-release"
        export SOURCE_DATE_EPOCH=$(date +%s)
        echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH"
        echo 'sbt -J-XX:MaxMetaspaceSize=1024m -J-Xmx2048m -v clean +test +packagedArtifacts ci-release devOopsGitHubReleaseUploadArtifacts'
        sbt \
        -J-XX:MaxMetaspaceSize=1024m \
        -J-Xmx2048m \
        -v \
        clean \
        compile \
        packagedArtifacts \
        ci-release

